import { Hotel } from "./types"

export const hotels: Hotel[] = [
  {
    id: "1", name: "The Grand Palace", location: "Downtown, Manhattan", city: "New York",
    image: "🏨", gallery: ["lobby", "pool", "room", "restaurant", "spa"],
    rating: 4.8, reviews: 3240, stars: 5, pricePerNight: 420, originalPrice: 560,
    description: "An iconic luxury hotel in the heart of Manhattan with breathtaking skyline views, world-class dining, and an award-winning spa.",
    amenities: ["Pool", "Spa", "Gym", "Wi-Fi", "Restaurant", "Bar", "Room Service", "Concierge", "Valet Parking", "Business Center"],
    roomTypes: [
      { id: "r1", name: "Deluxe King", price: 420, originalPrice: 560, capacity: 2, bedType: "King", size: "45 sqm", amenities: ["City View", "Mini Bar", "Rain Shower", "Smart TV"], image: "🛏️", available: 5, description: "Spacious room with panoramic city views" },
      { id: "r2", name: "Premium Suite", price: 680, originalPrice: 850, capacity: 3, bedType: "King + Sofa", size: "72 sqm", amenities: ["City View", "Mini Bar", "Jacuzzi", "Living Area", "Smart TV", "Nespresso"], image: "🛋️", available: 3, description: "Luxurious suite with separate living area" },
      { id: "r3", name: "Presidential Suite", price: 1200, originalPrice: 1500, capacity: 4, bedType: "King + Twin", size: "120 sqm", amenities: ["Panoramic View", "Private Bar", "Jacuzzi", "Dining Room", "Butler Service", "Terrace"], image: "👑", available: 1, description: "The ultimate luxury experience with butler service" },
    ],
    checkIn: "3:00 PM", checkOut: "11:00 AM",
    policies: ["Free cancellation until 48h before check-in", "No smoking", "Pets allowed (fee applies)", "ID required at check-in"],
    highlights: ["Rooftop infinity pool", "Michelin-star restaurant", "24/7 concierge", "Central Park views"],
    coordinates: { lat: 40.7614, lng: -73.9776 }, freeCancellation: true, breakfastIncluded: true, provider: "Direct", badge: "Best Seller",
  },
  {
    id: "2", name: "Skyline Boutique Hotel", location: "Midtown, Times Square", city: "New York",
    image: "🌆", gallery: ["exterior", "room", "lounge", "terrace", "breakfast"],
    rating: 4.5, reviews: 1890, stars: 4, pricePerNight: 280, originalPrice: 350,
    description: "A chic boutique hotel steps from Times Square with designer interiors and a stunning rooftop terrace.",
    amenities: ["Wi-Fi", "Gym", "Restaurant", "Bar", "Room Service", "Rooftop Terrace", "Laundry"],
    roomTypes: [
      { id: "r1", name: "Standard Queen", price: 280, originalPrice: 350, capacity: 2, bedType: "Queen", size: "30 sqm", amenities: ["City View", "Smart TV", "Coffee Maker"], image: "🛏️", available: 8, description: "Comfortable room with modern amenities" },
      { id: "r2", name: "Superior King", price: 380, originalPrice: 480, capacity: 2, bedType: "King", size: "40 sqm", amenities: ["City View", "Mini Bar", "Rain Shower", "Smart TV"], image: "🛏️", available: 4, description: "Upgraded room with premium furnishings" },
    ],
    checkIn: "2:00 PM", checkOut: "12:00 PM",
    policies: ["Free cancellation until 24h before check-in", "No smoking", "No pets"],
    highlights: ["Rooftop bar with skyline views", "Walking distance to Broadway", "Complimentary breakfast"],
    coordinates: { lat: 40.7580, lng: -73.9855 }, freeCancellation: true, breakfastIncluded: true, provider: "Booking.com",
  },
  {
    id: "3", name: "Harbor View Resort", location: "Waterfront, Brooklyn", city: "New York",
    image: "⛵", gallery: ["harbor", "pool", "suite", "dining", "gym"],
    rating: 4.6, reviews: 2100, stars: 4, pricePerNight: 320, originalPrice: 400,
    description: "A waterfront resort offering stunning harbor views, an outdoor pool, and easy access to Brooklyn's vibrant culture.",
    amenities: ["Pool", "Spa", "Gym", "Wi-Fi", "Restaurant", "Bar", "Kayaking", "Bike Rental", "Parking"],
    roomTypes: [
      { id: "r1", name: "Harbor View Room", price: 320, originalPrice: 400, capacity: 2, bedType: "King", size: "38 sqm", amenities: ["Harbor View", "Balcony", "Smart TV", "Coffee Maker"], image: "🛏️", available: 6, description: "Wake up to stunning harbor views" },
      { id: "r2", name: "Waterfront Suite", price: 520, originalPrice: 650, capacity: 3, bedType: "King + Sofa", size: "65 sqm", amenities: ["Harbor View", "Balcony", "Living Area", "Mini Bar", "Jacuzzi"], image: "🛋️", available: 2, description: "Spacious suite with private balcony" },
    ],
    checkIn: "3:00 PM", checkOut: "11:00 AM",
    policies: ["Free cancellation until 72h before check-in", "No smoking indoors", "Pets welcome"],
    highlights: ["Outdoor infinity pool", "Private beach access", "Water sports center", "Sunset dining"],
    coordinates: { lat: 40.6892, lng: -73.9857 }, freeCancellation: true, breakfastIncluded: false, provider: "Expedia", badge: "Waterfront",
  },
  {
    id: "4", name: "The Artisan Loft", location: "SoHo, Manhattan", city: "New York",
    image: "🎨", gallery: ["loft", "gallery", "room", "cafe", "courtyard"],
    rating: 4.7, reviews: 980, stars: 4, pricePerNight: 350, originalPrice: 420,
    description: "An art-inspired boutique hotel in SoHo featuring curated galleries, artisan coffee, and loft-style rooms.",
    amenities: ["Wi-Fi", "Art Gallery", "Café", "Gym", "Courtyard", "Library", "Bike Rental"],
    roomTypes: [
      { id: "r1", name: "Artist Loft", price: 350, originalPrice: 420, capacity: 2, bedType: "King", size: "42 sqm", amenities: ["Loft Ceiling", "Art Pieces", "Rain Shower", "Vinyl Player"], image: "🎨", available: 4, description: "Industrial-chic loft with curated art" },
      { id: "r2", name: "Gallery Suite", price: 550, originalPrice: 680, capacity: 2, bedType: "King", size: "58 sqm", amenities: ["Private Gallery", "Terrace", "Freestanding Tub", "Mini Bar"], image: "🖼️", available: 2, description: "Suite with private art collection" },
    ],
    checkIn: "3:00 PM", checkOut: "12:00 PM",
    policies: ["Free cancellation until 48h before check-in", "No smoking", "No pets"],
    highlights: ["Rotating art exhibitions", "Artisan coffee bar", "SoHo shopping district", "Courtyard garden"],
    coordinates: { lat: 40.7233, lng: -73.9985 }, freeCancellation: true, breakfastIncluded: false, provider: "Direct", badge: "Unique Stay",
  },
  {
    id: "5", name: "Central Park Residence", location: "Upper West Side", city: "New York",
    image: "🌳", gallery: ["park", "lobby", "room", "restaurant", "terrace"],
    rating: 4.9, reviews: 4500, stars: 5, pricePerNight: 580, originalPrice: 750,
    description: "An ultra-luxury residence overlooking Central Park with Michelin-starred dining and a world-class wellness center.",
    amenities: ["Pool", "Spa", "Gym", "Wi-Fi", "Restaurant", "Bar", "Room Service", "Concierge", "Valet Parking", "Wellness Center", "Tennis Court"],
    roomTypes: [
      { id: "r1", name: "Park View Deluxe", price: 580, originalPrice: 750, capacity: 2, bedType: "King", size: "50 sqm", amenities: ["Park View", "Mini Bar", "Marble Bath", "Smart TV", "Nespresso"], image: "🛏️", available: 3, description: "Elegant room with Central Park views" },
      { id: "r2", name: "Park Suite", price: 920, originalPrice: 1150, capacity: 3, bedType: "King + Sofa", size: "85 sqm", amenities: ["Park View", "Living Room", "Dining Area", "Butler Service", "Terrace"], image: "🛋️", available: 2, description: "Expansive suite with park panorama" },
      { id: "r3", name: "Penthouse", price: 2200, originalPrice: 2800, capacity: 4, bedType: "2 Kings", size: "200 sqm", amenities: ["360° Views", "Private Pool", "Chef's Kitchen", "Butler", "Home Theater", "Wine Cellar"], image: "👑", available: 1, description: "The pinnacle of luxury living" },
    ],
    checkIn: "3:00 PM", checkOut: "12:00 PM",
    policies: ["Free cancellation until 72h before check-in", "No smoking", "Pets allowed", "Dress code for restaurant"],
    highlights: ["Central Park frontage", "2 Michelin-star restaurant", "Holistic wellness center", "Private park access"],
    coordinates: { lat: 40.7812, lng: -73.9665 }, freeCancellation: true, breakfastIncluded: true, provider: "Direct", badge: "Top Rated",
  },
  {
    id: "6", name: "Metro Express Inn", location: "Chelsea, Manhattan", city: "New York",
    image: "🏢", gallery: ["exterior", "room", "lobby", "breakfast"],
    rating: 4.1, reviews: 5600, stars: 3, pricePerNight: 150, originalPrice: 190,
    description: "A value-friendly hotel in Chelsea with clean, modern rooms and excellent subway access.",
    amenities: ["Wi-Fi", "Gym", "Breakfast", "Laundry", "Business Center", "Luggage Storage"],
    roomTypes: [
      { id: "r1", name: "Standard Double", price: 150, originalPrice: 190, capacity: 2, bedType: "Double", size: "22 sqm", amenities: ["Smart TV", "Coffee Maker", "Desk"], image: "🛏️", available: 12, description: "Clean and comfortable essentials" },
      { id: "r2", name: "Superior Twin", price: 180, originalPrice: 230, capacity: 2, bedType: "Twin", size: "26 sqm", amenities: ["Smart TV", "Coffee Maker", "Desk", "Mini Fridge"], image: "🛏️", available: 8, description: "Spacious twin room for friends" },
    ],
    checkIn: "2:00 PM", checkOut: "11:00 AM",
    policies: ["Free cancellation until 24h before check-in", "No smoking", "No pets"],
    highlights: ["Steps from subway", "Free continental breakfast", "24/7 front desk", "Great value"],
    coordinates: { lat: 40.7465, lng: -74.0014 }, freeCancellation: true, breakfastIncluded: true, provider: "Hotels.com", badge: "Value Pick",
  },
  {
    id: "7", name: "The Zen Garden Hotel", location: "East Village", city: "New York",
    image: "🧘", gallery: ["garden", "spa", "room", "meditation", "restaurant"],
    rating: 4.7, reviews: 1450, stars: 4, pricePerNight: 310, originalPrice: 380,
    description: "A wellness-focused hotel with Japanese-inspired design, meditation gardens, and an organic restaurant.",
    amenities: ["Spa", "Meditation Room", "Yoga Studio", "Wi-Fi", "Organic Restaurant", "Garden", "Sauna"],
    roomTypes: [
      { id: "r1", name: "Zen Room", price: 310, originalPrice: 380, capacity: 2, bedType: "King", size: "35 sqm", amenities: ["Garden View", "Tatami Area", "Rain Shower", "Tea Set"], image: "🍵", available: 6, description: "Minimalist room with zen garden view" },
      { id: "r2", name: "Onsen Suite", price: 480, originalPrice: 600, capacity: 2, bedType: "King", size: "55 sqm", amenities: ["Private Onsen", "Garden View", "Meditation Corner", "Tea Ceremony Set"], image: "♨️", available: 2, description: "Suite with private hot spring bath" },
    ],
    checkIn: "3:00 PM", checkOut: "11:00 AM",
    policies: ["Free cancellation until 48h before check-in", "No smoking", "No pets", "Quiet hours 10 PM - 7 AM"],
    highlights: ["Japanese zen garden", "Daily yoga classes", "Organic farm-to-table dining", "Sound healing sessions"],
    coordinates: { lat: 40.7264, lng: -73.9818 }, freeCancellation: true, breakfastIncluded: true, provider: "Direct",
  },
  {
    id: "8", name: "Brooklyn Bridge Hotel", location: "DUMBO, Brooklyn", city: "New York",
    image: "🌉", gallery: ["bridge", "rooftop", "room", "bar", "view"],
    rating: 4.4, reviews: 2800, stars: 4, pricePerNight: 260, originalPrice: 330,
    description: "A trendy hotel in DUMBO with iconic Brooklyn Bridge views, a rooftop bar, and industrial-chic design.",
    amenities: ["Wi-Fi", "Rooftop Bar", "Gym", "Restaurant", "Bike Rental", "Co-working Space", "Laundry"],
    roomTypes: [
      { id: "r1", name: "Bridge View Room", price: 260, originalPrice: 330, capacity: 2, bedType: "Queen", size: "32 sqm", amenities: ["Bridge View", "Smart TV", "Coffee Maker", "Desk"], image: "🛏️", available: 7, description: "Room with iconic bridge views" },
      { id: "r2", name: "Loft King", price: 380, originalPrice: 470, capacity: 2, bedType: "King", size: "48 sqm", amenities: ["Bridge View", "Loft Ceiling", "Mini Bar", "Rain Shower", "Vinyl Player"], image: "🛏️", available: 3, description: "Industrial loft with premium amenities" },
    ],
    checkIn: "3:00 PM", checkOut: "12:00 PM",
    policies: ["Free cancellation until 24h before check-in", "No smoking", "Dogs allowed"],
    highlights: ["Brooklyn Bridge panorama", "Rooftop cocktail bar", "DUMBO art galleries", "Waterfront promenade"],
    coordinates: { lat: 40.7033, lng: -73.9903 }, freeCancellation: true, breakfastIncluded: false, provider: "Booking.com",
  },
]

export const popularDestinations = [
  { city: "New York", country: "USA", image: "🗽", hotels: 2400, startingPrice: 150 },
  { city: "Paris", country: "France", image: "🗼", hotels: 1800, startingPrice: 180 },
  { city: "Tokyo", country: "Japan", image: "🗾", hotels: 2100, startingPrice: 120 },
  { city: "London", country: "UK", image: "🎡", hotels: 1950, startingPrice: 160 },
  { city: "Dubai", country: "UAE", image: "🏙️", hotels: 1200, startingPrice: 200 },
  { city: "Bali", country: "Indonesia", image: "🌴", hotels: 900, startingPrice: 80 },
]

export const cities = [
  "New York", "Los Angeles", "Chicago", "Miami", "San Francisco",
  "Las Vegas", "Boston", "Seattle", "Washington DC", "Orlando",
  "Paris", "London", "Tokyo", "Dubai", "Bali", "Barcelona",
  "Rome", "Amsterdam", "Bangkok", "Singapore",
]
